# Generated by Django 4.2.20 on 2025-03-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'permissions': [('can_submit_PDF', 'Can submit PDF'), ('can_communicate', 'Can communicate')],
            },
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_mark_reviewing', 'Can mark papers as reviewing'), ('can_mark_reviewed_Accept', 'Can mark papers as accepted'), ('can_mark_reviewed_Denied', 'Can mark papers as denied')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter Username', max_length=20, unique=True)),
                ('email', models.EmailField(help_text='Enter email', max_length=30)),
                ('password', models.EmailField(help_text='Enter email', max_length=30)),
                ('user_type', models.CharField(blank=True, choices=[('a', 'Author'), ('e', 'Edtior'), ('r', 'Reviewer'), ('admin', 'Admin'), ('g', 'Guest')], default='g', help_text='Account Type', max_length=5)),
            ],
            options={
                'ordering': ['username', 'email'],
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
            ],
            options={
                'permissions': [('can_mark_editing', 'Can mark papers as editing'), ('can_mark_edited', 'Can mark papers as edited'), ('can_submit_comments_to_the_author', 'Can submit comments to the author'), ('can_submit_comments_to_the_author_and_reviewer', 'Can submit comments to the author and reviewer')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.reviewer',),
        ),
    ]
