# Generated by Django 4.2.20 on 2025-03-23 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_user_bio_user_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': [('can_submit_PDF', 'Can submit PDF'), ('can_communicate', 'Can communicate')]},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_access_dash', 'Can access dashboard')]},
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_author',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_editor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_reviewer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.role'),
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='editor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_mark_editing', 'Can mark papers as editing'), ('can_mark_edited', 'Can mark papers as edited'), ('can_submit_comments_to_the_author', 'Can submit comments to the author'), ('can_submit_comments_to_the_author_and_reviewer', 'Can submit comments to the author and reviewer')],
            },
        ),
    ]
