# Generated by Django 4.2.18 on 2025-04-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('abstract', models.CharField(max_length=100)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='news/')),
            ],
        ),
        migrations.RemoveField(
            model_name='poster',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='poster',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='posters/previews/'),
        ),
    ]
