# Generated by Django 4.2.18 on 2025-04-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='submitted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
