# Generated by Django 4.2.20 on 2025-03-25 23:22

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_submit_PDF', 'Can submit PDF'), ('can_communicate', 'Can communicate')],
            },
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter key words', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the paper', max_length=1000)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('article_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.author')),
                ('key_word', models.ManyToManyField(help_text='Select a key word for this paper', to='core.keyword')),
            ],
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='key_word_name_case_insensitive_unique', violation_error_message='Key word already exists (case insensitive match)'),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to='core.user'),
        ),
    ]
