# Generated by Django 4.2.18 on 2025-04-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_faq_news_remove_poster_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='preview_image',
        ),
        migrations.AddField(
            model_name='poster',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='posters/thumbnails/'),
        ),
    ]
