# Generated by Django 4.2.20 on 2025-04-14 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_editor_user_alter_reviewer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='submitted_date',
        ),
        migrations.AddField(
            model_name='poster',
            name='pdf',
            field=models.FileField(default='pdf', upload_to='posters/'),
        ),
        migrations.AddField(
            model_name='poster',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
