# Generated by Django 4.2.20 on 2025-04-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_poster_submitted_date_poster_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='poster',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
