# Generated by Django 4.2.18 on 2025-04-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='key_word',
        ),
        migrations.AddField(
            model_name='paper',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
