# Generated by Django 4.2.20 on 2025-04-14 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_poster_uploaded_at_alter_poster_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
