# Generated by Django 4.2.18 on 2025-04-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_paper_key_word_paper_is_edited_delete_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='papers/'),
        ),
    ]
