# Generated by Django 4.2.20 on 2025-04-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_poster_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='posters/thumbnails/'),
        ),
    ]
