# Generated by Django 4.2.18 on 2025-04-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_paper_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='denied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='editor_reached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='reviewer_reached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='subimtted',
            field=models.BooleanField(default=False),
        ),
    ]
