# Generated by Django 4.2.18 on 2025-04-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paper_approved_paper_denied_paper_editor_reached_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='file',
            new_name='pdf',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='denied',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='editor_reached',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='reviewer_reached',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='subimtted',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='summary',
        ),
        migrations.AddField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('WIP', 'WIP'), ('submitted', 'Submitted'), ('editor_reached', 'Editor_reached'), ('reviewer_reached', 'Reviewer_reached'), ('approved', 'Approved'), ('denied', 'Denied')], default='WIP', max_length=20),
        ),
    ]
