# Generated by Django 4.2.18 on 2025-04-30 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_file_paper_pdf_remove_paper_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
