# Generated by Django 4.2.20 on 2025-04-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'User'), ('author', 'Author'), ('reviewer', 'Reviewer'), ('editor', 'Editor'), ('basic', 'Basic')], default='basic', max_length=20),
        ),
    ]
